version: '3.5'
services:
  nest-app:
    build: .
    image: nest_app
    container_name: nest_app_container
    command: npm start
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - .:/var/www
    networks:
      - node-network
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-nestdb}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
    volumes:
      - ${DOCKER_VOLUMN:-~/.docker/data}/postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - node-network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ${DOCKER_VOLUMN:-~/.docker/data}/pgadmin:/root/.pgadmin
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    networks:
      - node-network
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    privileged: true
    ports:
      - 6379:6379
    networks:
      - node-network
volumes:
  dbdata:
  pgadmin:
  node_modules:

networks:
  node-network:
    driver: bridge
