name: Node.js CI

on:
  push:
    branches: [main, develop]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    rbuild:
    uses: ./.github/workflows/ci.yml
  # deploy:
  #   runs-on: ubuntu-latest
  #   stepss:
  #     - name: Install SSH Key
  #       uses: shimataro/ssh-key-action@v2
  #       with:
  #         key: ${{ cd_env.SSH_PRIVATE_KEY }}
  #         known_hosts: 'cd_host'
  #     - name: Adding Known Hosts
  #       run: ssh-keyscan -H ${{ cd_env.SSH_HOST }} >> ~/.ssh/known_hosts
  #     - name: Deploy with rsync
  #       run: rsync -avz ./dist/ ${{ cd_env.SSH_USER }}@${{ cd_env.SSH_HOST }}:/root/dist/
