name: Node.js CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379

    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: ['4.2']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm ci
      - run: npm run lint
      - run: npm run ts-check
      - run: npm run build --if-present
      - name: Run tests
        run: npm test
        env:
          CI: true
  # deploy:
  #   runs-on: ubuntu-latest
  #   stepss:
  #     - name: Install SSH Key
  #       uses: shimataro/ssh-key-action@v2
  #       with:
  #         key: ${{ cd_env.SSH_PRIVATE_KEY }}
  #         known_hosts: 'cd_host'
  #     - name: Adding Known Hosts
  #       run: ssh-keyscan -H ${{ cd_env.SSH_HOST }} >> ~/.ssh/known_hosts
  #     - name: Deploy with rsync
  #       run: rsync -avz ./dist/ ${{ cd_env.SSH_USER }}@${{ cd_env.SSH_HOST }}:/root/dist/
